apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: gestbib
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'auth-service'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['auth-service:3000']

      - job_name: 'catalog-service'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['catalog-service:3001']

      - job_name: 'borrow-service'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['borrow-service:3002']
